2024-09-10 17:06:28,600 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\agafu\Desktop\Urban\homework\test_12_4.py", line 65, in test_run
    r2 = Runner(5)
         ^^^^^^^^^
  File "C:\Users\agafu\Desktop\Urban\homework\test_12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-09-10 17:06:28,601 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\agafu\Desktop\Urban\homework\test_12_4.py", line 58, in test_walk
    r1 = Runner('Вася', -1)
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\agafu\Desktop\Urban\homework\test_12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -1
